apiVersion: v1
kind: Namespace
metadata:
  name: jmeter
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-app-service
  namespace: jmeter
spec:
  selector:
    app: jmeter-master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-communication
  namespace: jmeter
spec:
  podSelector:
    matchLabels:
      app: jmeter-master
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: jmeter-master
    - podSelector:
        matchLabels:
          app: jmeter-slave
  - from:
    - podSelector:
        matchLabels:
          app: jmeter-slave
    - podSelector:
        matchLabels:
          app: jmeter-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
    spec:
      containers:
      - name: jmeter-master
        image: mnazim1541/jmmaster:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'Waiting for JMeter slaves...'; sleep infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slave
  namespace: jmeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmeter-slave
  template:
    metadata:
      labels:
        app: jmeter-slave
    spec:
      containers:
      - name: jmeter-slave
        image: mnazim1541/jmslave:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'JMeter slave is ready'; sleep infinity"]
