apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: slave
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: mnazim1541/jmmaster:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'JMeter master is ready'; sleep infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
      - name: slave
        image: mnazim1541/jmslave:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'JMeter slave is ready'; sleep infinity"]


