apiVersion: v1
kind: Namespace
metadata:
  name: jmeter
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-service
  namespace: jmeter
spec:
  selector:
    run: jemeter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-master
  template:
    metadata:
      labels:
        app: jmeter-master
        run: jemeter
    spec:
      containers:
      - name: jmeter-master
        image: mnazim1541/jmmaster:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'Waiting for JMeter slaves...'; sleep infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slave
  namespace: jmeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jmeter-slave
  template:
    metadata:
      labels:
        app: jmeter-slave
        run: jemeter
    spec:
      containers:
      - name: jmeter-slave
        image: mnazim1541/jmslave:latest
        command: ["/bin/sh", "-c"]
        args: ["echo 'JMeter slave is ready'; sleep infinity"]
