pipeline {

    agent any

    tools {
        nodejs '20.8.0'

    }

    stages {
        stage('Checkout') {
            steps {
                // Bitbucket'tan kodu çek
                // git 'https://gobitbucket.havelsan.com.tr/scm/test-md/doob_api_tests.git'
                echo 'git atlandı'
            }
        }

        
        stage('Install npm') {
            steps {
                // Node.js için Yarn kullanarak bağımlılıkları yükle
                sh 'npm version'
                // sh 'yarn install'
            }
        }

        stage('Install Dependencies') {
            steps {
                // Node.js için Yarn kullanarak bağımlılıkları yükle
                sh 'yarn --version'
                // sh 'yarn install'
            }
        }
    }

    post {
        always {
            // clean up
            deleteDir()
        }

        success {
            echo 'SUCCESS JENKINS'
        }

        failure {
            echo 'ERROR JENKINS'
        }
    }
}