pipeline {

    agent any

    tools {
        nodejs '20.8.0'
    }

    stages {
        stage('Checkout1') {
            steps {
                // Bitbucket kimlik bilgileri
                git credentialsId: 'c2742d94-9f9c-45cd-90d1-f2ddcfe099c2', url: 'https://gobitbucket.havelsan.com.tr/scm/test-md/doob_api_tests.git', branch: 'master'
            }

        stage('Install Dependencies') {
            steps {
                // Node.js için Yarn kullanarak bağımlılıkları yükle
                sh 'yarn --version'
            }
        }
    }

    post {
        always {
            // clean up
            deleteDir()
        }

        success {
            echo 'SUCCESS JENKINS'
        }

        failure {
            echo 'ERROR JENKINS'
        }
    }
}