pipeline {

    agent {
        docker {
            image 'node:18.18.0-alpine3.18' 
            args '-p 3000:3000' 
        }
    }

    stages {
        stage('Checkout') {
            steps {
                // Bitbucket'tan kodu çek
                // git 'https://gobitbucket.havelsan.com.tr/scm/test-md/doob_api_tests.git'
                echo 'git atlandı'
            }
        }

        stage('Install Yarn globally') {
            steps {
                script {
                    sh 'npm install'
                    sh 'npm install --global yarn'
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                // Node.js için Yarn kullanarak bağımlılıkları yükle
                sh 'yarn --version'
                // sh 'yarn install'
            }
        }
    }

    post {
        always {
            // clean up
            deleteDir()
        }

        success {
            echo 'SUCCESS JENKINS'
        }

        failure {
            echo 'ERROR JENKINS'
        }
    }
}