apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: test
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
        - name: jmmaster
          image: ahmettoguz/jmeter-master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 60000
          command: ["/bin/sh", "-c"]
          args: ["sleep infinity"]
      imagePullSecrets:
        - name: registrypullsecret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  namespace: test
  labels:
    jmeter_mode: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: ahmettoguz/jmeter-slave
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: registrypullsecret
